function jcommercegae(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',hb='&',r='/',ec='<script defer="defer">jcommercegae.onInjectionDone(\'jcommercegae\')<\/script>',hc='<script id="',A='=',q='?',C='Bad handler "',cc='DOMContentLoaded',Ab="GWT module 'jcommercegae' needs to be (re)compiled, please run a compile or use the Compile/Browse button in hosted mode",o='SCRIPT',lb='Unexpected exception in locale detection, using default: ',kb='_',ib='__gwt_Locale',gc='__gwt_marker_jcommercegae',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',z='content',jb='default',fc='end',tb='gecko',ub='gecko1_8',yb='gwt.hybrid',Bb='gwt/standard/standard.css',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',ac='head',xb='hosted.html?jcommercegae',Fb='href',bc='iShop.css',sb='ie6',ab='iframe',t='img',bb="javascript:''",m='jcommercegae',Cb='link',wb='loadExternalRefs',fb='locale',gb='locale=',v='meta',eb='moduleRequested',dc='moduleStartup',rb='msie',w='name',ob='opera',db='position:absolute;width:0;height:0;border:none',Db='rel',qb='safari',zb='selectingPermutation',x='startup',Eb='stylesheet',vb='unknown',mb='user.agent',pb='webkit';var jc=window,k=document,ic=jc.__gwtStatsEvent?function(a){return jc.__gwtStatsEvent(a)}:null,Dc,tc,oc,nc=l,wc={},ad=[],Cc=[],mc=[],zc,Bc;ic&&ic({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!jc.__gwt_stylesLoaded){jc.__gwt_stylesLoaded={}}if(!jc.__gwt_scriptsLoaded){jc.__gwt_scriptsLoaded={}}function sc(){var b=false;try{b=jc.external&&(jc.external.gwtOnLoad&&jc.location.search.indexOf(yb)==-1)}catch(a){}sc=function(){return b};return b}
function vc(){if(Dc&&tc){var c=k.getElementById(m);var b=c.contentWindow;if(sc()){b.__gwt_getProperty=function(a){return pc(a)}}jcommercegae=null;b.gwtOnLoad(zc,m,nc);ic&&ic({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:fc})}}
function qc(){var j,h=gc,i;k.write(hc+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){nc=f(j.src)}if(nc==l){var e=k.getElementsByTagName(s);if(e.length>0){nc=e[e.length-1].href}else{nc=f(k.location.href)}}else if(nc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=nc+u;nc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function Ac(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}wc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{Bc=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{zc=eval(b)}catch(a){alert(C+b+F)}}}}}}
function lc(a,b){return b in ad[a]}
function kc(a){var b=wc[a];return b==null?null:b}
function pc(d){var e=Cc[d](),b=ad[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(Bc){Bc(d,a,e)}throw null}
var rc;function uc(){if(!rc){rc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);ic&&ic({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(nc+Ec)}}
Cc[fb]=function(){try{var g;if(g==null){var b=location.search;var h=b.indexOf(gb);if(h>=0){var e=b.substring(h);var c=e.indexOf(A)+1;var d=e.indexOf(hb);if(d==-1){d=e.length}g=e.substring(c,d)}}if(g==null){g=kc(fb)}if(g==null){g=jc[ib]}if(g==null){return jb}while(!lc(fb,g)){var f=g.lastIndexOf(kb);if(f==-1){g=jb;break}else{g=g.substring(0,f)}}return g}catch(a){alert(lb+a);return jb}};ad[fb]={'default':0,en:1,zh:2};Cc[mb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(ob)!=-1){return ob}else if(d.indexOf(pb)!=-1){return qb}else if(d.indexOf(rb)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return sb}}}else if(d.indexOf(tb)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return ub}return tb}return vb};ad[mb]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};jcommercegae.onScriptLoad=function(){if(rc){tc=true;vc()}};jcommercegae.onInjectionDone=function(){Dc=true;ic&&ic({moduleName:m,subSystem:x,evtGroup:wb,millis:(new Date()).getTime(),type:fc});vc()};qc();var Ec;if(sc()){if(jc.external.initModule&&jc.external.initModule(m)){jc.location.reload();return}Ec=xb}Ac();ic&&ic({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:zb});if(!Ec){try{alert(Ab);return}catch(a){return}}var yc;function xc(){if(!oc){oc=true;if(!__gwt_stylesLoaded[Bb]){var a=k.createElement(Cb);__gwt_stylesLoaded[Bb]=a;a.setAttribute(Db,Eb);a.setAttribute(Fb,nc+Bb);k.getElementsByTagName(ac)[0].appendChild(a)}if(!__gwt_stylesLoaded[bc]){var a=k.createElement(Cb);__gwt_stylesLoaded[bc]=a;a.setAttribute(Db,Eb);a.setAttribute(Fb,nc+bc);k.getElementsByTagName(ac)[0].appendChild(a)}vc();if(k.removeEventListener){k.removeEventListener(cc,xc,false)}if(yc){clearInterval(yc)}}}
if(k.addEventListener){k.addEventListener(cc,function(){uc();xc()},false)}var yc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){uc();xc()}},50);ic&&ic({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:fc});ic&&ic({moduleName:m,subSystem:x,evtGroup:wb,millis:(new Date()).getTime(),type:nb});k.write(ec)}
jcommercegae();